apiVersion: apps/v1
kind: Deployment
metadata:
  name: tzapp-deployment
  labels:
    app: tzapp
spec:
  replicas: 2

  selector:
    matchLabels:
      app: tzapp

  template:
    metadata:
      labels:
        app: tzapp

    spec:
      containers:
        - name: tzapp
          image: sem5075/tzapp:1.0
          ports:
            - containerPort: 32777